@startjson
{
  "Користувач": {
    "Логін": "JohnDoe",
    "Пароль": "securepassword123",
    "Ел. Пошта": "johndoe@email.com",
    "Запит на замовлення": [
      {
        "Дата": "2023-10-10",
        "Ціна": 55,
        "Книга": [
          {
            "Назва": "Війна і мир",
            "Автор": "Лев Толстой",
            "Ціна": 25
          },
          {
            "Назва": "1984",
            "Автор": "Джордж Оруелл",
            "Ціна": 30
          }
        ]
      }
    ]
  }
}
@endjson
